version: "3"
services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres
  telegram-bot-api:
    image: mykola2312/telegram-bot-api:latest
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - tg-data:/var/lib/telegram-bot-api
volumes:
  db-data:
  tg-data: